stages:
  - test

variables:
  BASE_URL: 'https://example.cypress.io'

test:
  image: cypress/browsers:22.12.0
  stage: test
  script:
    - npm ci
    - npx cypress run --browser chrome --config baseUrl=$BASE_URL
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day
    