stages:
  - test
  - deploy

variables:
  BASE_URL: 'https://example.cypress.io'
  SPEC_FILE: 'cypress/e2e/1-getting-started/todo.cy.js'

test:
  image: cypress/browsers:22.12.0
  stage: test
  script:
    - npm ci
    - npx cypress run --browser chrome --config baseUrl=$BASE_URL --spec "$SPEC_FILE"
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
  when: manual 
  needs:
    - job: test 
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    